data: [ {
  "firstName": "Jane",
  "lastName": "Doe",
  "birthdate": "1973-03-12",
  "email": "jadoe@fake.com",
  "phone": "8005555555",
  "street1": "1 Main St.",
  "street2": "Apartment A",
  "city": "Anytown",
  "stateProvince": "KS",
  "postalCode": "12345",
  "country": "USA"
},
{
  "firstName": "John",
  "lastName": "Doe",
  "birthdate": "1970-05-09",
  "email": "jdoe@fake.com",
  "phone": "8005555555",
  "street1": "1 Main St.",
  "street2": "Apartment A",
  "city": "Anytown",
  "stateProvince": "KS",
  "postalCode": "12345",
  "country": "USA"
},
{
  "firstName": "Danny",
  "lastName": "Real",
  "birthdate": "1990-12-31",
  "email": "reallyreal@real.com",
  "phone": "5558675309",
  "street1": "55 Side Ave.",
  "street2": "Nada",
  "city": "Thistown",
  "stateProvince": "AL",
  "postalCode": "98765",
  "country": "USA"
},
{
  "firstName": "Alphie",
  "lastName": "Thomas",
  "birthdate": "1958-07-23",
  "email": "zebest@new.com",
  "phone": "3258897744",
  "street1": "8956 Bain Ct",
  "city": "Jacksonville",
  "stateProvince": "FL",
  "postalCode": "32202",
  "country": "USA"
},
{
  "firstName": "Brooke",
  "lastName": "Zuel",
  "birthdate": "2001-07-04",
  "email": "admin@sports.ca.com",
  "phone": "800-555-1234",
  "street1": "2665 Yonge St",
  "street2": "",
  "city": "Toronto",
  "stateProvince": "CA",
  "postalCode": "M4P2J6",
  "country": "USA"
}]